spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cuisenio
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      continue-on-error: true
 # debug: true
#logging:
 # level:
   # root: DEBUG