export const routes = {
    auth: {
      base: "/v1/auth",
      login: "/v1/auth/login",
      register: "/v1/auth/register",
      google: "/v1/auth/google",
      verify: "/v1/auth/verify-token",
      forgotPassword: "/v1/auth/forgot-password",
      resetPassword: "/v1/auth/reset-password",
      verifyResetToken: (token: string) => `/v1/auth/reset-password/verify/${token}`,
    },
    categories: {
      base: '/v1/categories',
      detail: (id: number) => `/v1/categories/${id}`,
      adminTags: "/v1/admin/tags",
      adminTagDetail: (id: number) => `/v1/admin/tags/${id}`,
    },
    ingredients: {
      base: '/v1/ingredients',
      detail: (id: number) => `/v1/ingredients/${id}`,
      count: '/v1/ingredients/count',
      masterBase: "/v1/admin/master-ingredients",
      masterDetail: (id: number) => `/v1/admin/master-ingredients/${id}`,
      alias: "/v1/admin/ingredients/alias",
      normalize: "/v1/ingredients/normalize-quantity",
    },
    profile: "/v1/profile",

    recipes: {
      base: '/api/recipes',
      homepageHero: "/api/homepage/hero",
      detail: (publicId: string) => `/api/recipes/${publicId}`,
      byPublicId: (publicId: string) => `/api/recipes/public/${publicId}`,
      comments: (publicId: string) => `/api/recipes/${publicId}/comments`,
      likes: (publicId: string) => `/api/recipes/${publicId}/likes`,
      report: (publicId: string) => `/api/recipes/${publicId}/report`,
      reportComment: (recipePublicId: string, commentId: number) => `/api/recipes/${recipePublicId}/comments/${commentId}/report`,
      unsave: (publicId: string) => `/api/recipes/${publicId}/unsave`,
      saved: "/api/recipes/saved",
      search: "/api/recipes/search",
      addImage: (publicId: string) => `/api/recipes/add-image/${publicId}`,
      submitForReview: (publicId: string) => `/api/recipes/${publicId}/submit-review`,
      approve: (id: number) => `/admin/recipes/approve/${id}`,
      moderationQueue: "/v1/admin/recipes/moderation-queue",
      moderationStatus: (id: number) => `/v1/admin/recipes/${id}/moderation`,
      moderationReports: "/v1/admin/moderation/reports",
      promotion: (id: number) => `/v1/admin/recipes/${id}/promotion`,
      restore: (id: number) => `/api/admin/recipes/${id}/restore`,
    },
    users: {
        base: '/v1/admin/users',
        detail: (id: number) => `/v1/admin/users/${id}`,
        count: '/v1/admin/users/count',
        block: (id: number) => `/v1/admin/users/${id}/block`,
        unblock: (id: number) => `/v1/admin/users/${id}/unblock`,
        stats: '/v1/admin/stats',
        overview: "/v1/admin/overview",
        status: (id: number) => `/v1/admin/users/${id}/status`,
        role: (id: number) => `/v1/admin/users/${id}/role`,
        archive: (id: number) => `/v1/admin/users/${id}/archive`,
      },
    mealPlanner: {
      base: '/v1/meal-plans',
      create: (recipePublicId: string) => `/v1/meal-plans/${recipePublicId}`,
      detail: (publicId: string) => `/v1/meal-plans/${publicId}`,
      smartGenerate: '/v1/meal-plans/smart/generate',
      shoppingList: '/v1/meal-plans/smart/shopping-list',
    },
    recipeImport: {
      preview: '/v1/recipes/import/preview',
    },
    newsletter: {
      subscribe: '/api/newsletter/subscribe',
      unsubscribe: '/api/newsletter/unsubscribe',
      adminList: '/v1/admin/newsletter/subscribers',
      adminDetail: (id: number) => `/v1/admin/newsletter/subscribers/${id}`,
      adminUnsubscribe: (id: number) => `/v1/admin/newsletter/subscribers/${id}/unsubscribe`,
    },
    notifications: {
      base: '/api/notifications',
      unreadCount: '/api/notifications/unread-count',
      read: (id: number) => `/api/notifications/${id}/read`,
      readAll: '/api/notifications/read-all',
    },
  };